### ISSUE TITLE
I have a question. Please help me answer it.

### ISSUE THREAD

**Issue by jy-98** [ahmed-guedmioui/Dictionary-App#2]
![549981710383681_ pic](https://github.com/ahmed-guedmioui/Dictionary-App/assets/57749560/dfdfd4fb-02db-4cf2-9489-8a6f701619d6)
![549991710383681_ pic](https://github.com/ahmed-guedmioui/Dictionary-App/assets/57749560/663e8de9-335d-415e-adfd-0afc6eb0bbf7)
![550001710383681_ pic](https://github.com/ahmed-guedmioui/Dictionary-App/assets/57749560/2d34b519-36f8-43a9-a233-44af3f9c357b)

Why do I want to make a mapper converter?

When the api is obtained, it is the xxxdto object. After the network data is obtained, the xxxdto object is converted into the xxx object, but the data format is the same. Wouldn't this be cumbersome?

**Comment by ahmed-guedmioui** [comment]
There will be a video in my channel on 15/Mar answering your question

**Comment by jy-98** [comment]
Thank you. I saw it. I hope the videos will get better and better in the future. I’m looking forward to it.😊
